// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0K48XwOM0qkprrb9g7Wnno9QlJLFKs6g',
    appId: '1:17933320646:android:73b5db517a6764e33ff2c7',
    messagingSenderId: '17933320646',
    projectId: 'trabalho-final-flutter-692bb',
    storageBucket: 'trabalho-final-flutter-692bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBkS90pEpChXErumj5vgbCC41ZNZTSBCs',
    appId: '1:17933320646:ios:b5c3a90f42c36a783ff2c7',
    messagingSenderId: '17933320646',
    projectId: 'trabalho-final-flutter-692bb',
    storageBucket: 'trabalho-final-flutter-692bb.appspot.com',
    iosClientId: '17933320646-5p9r60pgkkudv1g7lltv1iq8s0pgi35n.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoFinalFlutter',
  );
}
